### ISSUE TITLE
Move Vault of Satoshi to main section of Exchanges on front page

### ISSUE THREAD

**Issue by MeBeingAwesome** [super3/peercoin_website_old#108]
Move Vault of Satoshi to main section of Exchanges on front page. We need them featured prominently because they offer USD/PPC trading.

**Comment by super3** [comment]
@ngbatnicdotmil can you take care of this?

**Comment by ngbatnicdotmil** [comment]
sorry I didn't get you

Date: Sun, 5 Jan 2014 11:29:31 -0800
