### ISSUE TITLE
Add Press Links

### ISSUE THREAD

**Issue by JohnManglaviti** [super3/peercoin_website_old#109]
As requested, I populated the posts. Please create a Press dropdown for the following links:

Press - Press Kit

http://www.peercointalk.org/index.php?topic=1616.0

Press - Articles and Interviews

http://www.peercointalk.org/index.php?topic=1603.0

Press - Schedule an Interview with Sunny King

(Simple form where they could send Sunny an email, have it send to:

sunnyking9999@gmail.com
john.manglaviti@gmail.com )

**Comment by Sentinelrv** [comment]
John, that Coindesk article has the wrong title. Also, should we include the New York Times article?

**Comment by JohnManglaviti** [comment]
1. Coindesk article fixed, thanks.
2. I don't want to pick and choose links, I have no time to do that.  If the community wants to setup some type of 'remove' option, I'm fine with it.   Right now, we need something.
