### ISSUE TITLE
Replace wordpress template with new proposed one.

### ISSUE THREAD

**Issue by hammyburger** [super3/peercoin_website_old#11]
As per the discussion on peercointalk - a number of us would like to propose replacing the template for the website with this one: 

http://m.elgendy.me/demo/justone/?skin=dark

Let us how we can help.

**Comment by Sentinelrv** [comment]
My main reason for supporting this is because I want the main features and content of the website to be displayed at the top in the most visible location and not hidden down below where less people will be exposed to it. We need to make sure people see this information. It's one of the best ways to spread awareness of Peercoin's features.

If we could incorporate drop down menus into the current theme and group certain items together in the main navigation, then maybe we could avoid switching to a new theme. We're going to have a lot of content, so we'll need to make sure we have plenty of space to feature it all in a highly visible location.

**Comment by super3** [comment]
I am going to say no for now. My reasons:

1) Very heavy javascript and lots of animation is going to lead to a slow and poorly loading website
2) Wordpress is now going to be updated and maintained
3) The template is not going to fit easily with the color scheme we want
4) There might be a template better than this out there that can address 1 and 3, which would bring my arguments down to only 2. 

The good: 
- The website looks flashy in a good way. New users will probably like it.
- Official blog built into the website will allow us to easily manage press, etc. 

That being said, I'm not the website dictator. If it is the general consensus that we want that template instead then these things need to happen:
- Someone needs to buy the template 
- Someone needs to writeup all the text for the website, and have multiple people approve it for accuracy and errors

**Comment by Sentinelrv** [comment]
I mentioned in the thread that we should remove all that animation and just have the image banner up there above the navigation, the text and logo.  I completely agree the animation isn't necessary and will slow down the website. We would also have to select the right colors to fit with our logo.

**Comment by super3** [comment]
Not really as easy as that. You would be stripping away parts of the code, and its unclear how that would affect the template. Could still take a performance hit even with that removed. Or I mean it would be much better after you removed it. I have no idea.

**Comment by Sentinelrv** [comment]
I'm not an expert on websites, so I don't know what to say here. Would it be possible to add drop down menus to the current website, that way we could group items together?

**Comment by super3** [comment]
Yup that can be done, and should be done. Just need know what links need to go in those dropdowns.

**Comment by Sentinelrv** [comment]
Well, Wiki, FAQ and Myths could all go under "Resources" or maybe "Education." We would need to figure out the right name to use. All the beginner how to stuff you're having put together could go under "Guides" maybe. How many main buttons are you willing to put up there before you say no more? I was thinking maybe 2 more and that's it. I at least didn't think it was too crowded yet.
