### ISSUE TITLE
Please Link our Social Media Sites

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#12]
Is it possible to link our current social media sites as those little icons somewhere at the top of the page where they'd be visible? These pages very important for marketing and keeping everyone updated and on the same page.

www.facebook.com/Peercoin
www.twitter.com/PeercoinPPC
www.youtube.com/OfficialPeercoin
www.reddit.com/r/peercoin

**Comment by Sentinelrv** [comment]
Super3, is it possible to do this before our big media push tomorrow? I'd love people to be able to join up on the different pages we have, but they need to be listed on the website first in order to see them.

**Comment by super3** [comment]
Sorry, been a bit busy. Where do you suggest I put the links?

**Comment by Sentinelrv** [comment]
Sorry, I didn't see your response here until now. As soon as I'm done working with our designer on the text, I'll ask people about this.

**Comment by super3** [comment]
Ok. I figured out where these could go. I'll work on it soon.

**Comment by Sentinelrv** [comment]
I believe I've solved this issue. Check here: https://github.com/super3/Peercoin.net/issues/19

**Comment by super3** [comment]
Per #19
