### ISSUE TITLE
Request: Add MarketCap to the front page

### ISSUE THREAD

**Issue by JohnManglaviti** [super3/peercoin_website_old#125]
I'd like to see the marketcap on the front page.  From the post we saw earlier today from OKCoin, it's clear that most don't have any idea how large Peercoin is in terms of market cap.

**Comment by super3** [comment]
Agreed. We can stick it right under 'Why Peercoin?'
It can have the price on the left, and market cap on the right updated in realtime with javascript.

**Comment by jvanoel** [comment]
Maybe even below the two buttons in the header. Then people see it right away for sure without any scrolling?

**Comment by super3** [comment]
Don't think that we have enough space for that to work on mobile too.

**Comment by jvanoel** [comment]
I'll make it so it fits. Here I just gave the <header> some more height: http://d.pr/i/FsUG
The background coin will be placed a bit more higher so it's in the center of the tagline like the desktop version.

If you think below "Why Peercoin" is better, it's fine as well though.

**Comment by super3** [comment]
Sure if it fits, and works on mobile that is fine. @jvanoel how good are you at js?

**Comment by jvanoel** [comment]
I'm not that into javascript. So if someone can fix the output for me, I can style it..

**Comment by super3** [comment]
Ok I'll try to figure that out.

**Comment by super3** [comment]
Can you make a mockup?

**Comment by Gnewt** [comment]
Where would market cap and price be sourced from?
