### ISSUE TITLE
Translations to German and Spanish

### ISSUE THREAD

**Issue by d5000** [super3/peercoin_website_old#129]
I can contribute translations into German and Spanish. Are the basic introductory articles now stable so I can translate them? How can I enter them in the system?

**Comment by super3** [comment]
So yes you can translate to german and spanish. Still trying to figure out a better system for translation. Let me get back to you on that.

**Comment by super3** [comment]
As per #54 I am going to install Fork CMS. This should provide us with the tools to easily handle translation.

**Comment by Gnewt** [comment]
I'm ready to write a Spanish translation. Shall I hold off until the CMS is implemented?

**Comment by super3** [comment]
You can write the translations, just going to have to copy paste them in the CMS. I'll try to get it working soon.

**Comment by Gnewt** [comment]
Sounds good. Do you have a preference now for how translations should be submitted or should the pull request hold off until a CMS?

**Comment by super3** [comment]
You can put in a pull, so that I see its ready if you want. No preference,
till I get something up and running.

On Wed, Jan 8, 2014 at 7:18 PM, Nick Mooney notifications@github.comwrote:

> Sounds good. Do you have a preference now for how translations should be
> submitted or should the pull request hold off until a CMS?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/super3/Peercoin.net/issues/129#issuecomment-31891006
> .

## 

Shawn Wilkinson
Student, Morehouse College
Bitcoin Developer/Entrepreneur/Enthusiast
(1P4QkLsujBPBZyUwDezikL4fUSs7JvFhPv)
me@super3.org
http://super3.org

**Comment by super3** [comment]
You can put in a pull, so that I see its ready if you want.

On Wed, Jan 8, 2014 at 7:18 PM, Nick Mooney notifications@github.comwrote:

> Sounds good. Do you have a preference now for how translations should be
> submitted or should the pull request hold off until a CMS?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/super3/Peercoin.net/issues/129#issuecomment-31891006
> .

## 

Shawn Wilkinson
Student, Morehouse College
Bitcoin Developer/Entrepreneur/Enthusiast
(1P4QkLsujBPBZyUwDezikL4fUSs7JvFhPv)
me@super3.org
http://super3.org

**Comment by d5000** [comment]
Ok, so Gnewt you can do the Spanish one? Then I will do only the German translation. Thanks!

**Comment by Gnewt** [comment]
I definitely can, but I am not a native Spanish speaker so I'd love some review by others first. If someone who speaks Spanish natively would like to do the translation I'd defer to them.

**Comment by d5000** [comment]
I am a native speaker in both languages (German and Argentine Spanish). So I can review your spanish translation.

**Comment by d5000** [comment]
OK, first draft of German translation of the start page is almost complete (with the exception of Myth#2 - #135 - where we must see how we can change it). I have noted some parts of the page could be more newbie-friendly. Would it be OK if I change them a little bit (in my translation) and explain terms like "proof of work", above all in the FAQ section?

**Comment by super3** [comment]
Sure.

On Thu, Jan 9, 2014 at 10:25 PM, d5000 notifications@github.com wrote:

> OK, first draft of German translation of the start page is almost complete
> (with the exception of Myth #2https://github.com/super3/Peercoin.net/issues/2where we must see how we can change it). I have noted some parts of the
> page could be more newbie-friendly. Would it be OK if I change them a
> little bit (in my translation)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/super3/Peercoin.net/issues/129#issuecomment-31999874
> .

## 

Shawn Wilkinson
Student, Morehouse College
Bitcoin Developer/Entrepreneur/Enthusiast
(1P4QkLsujBPBZyUwDezikL4fUSs7JvFhPv)
me@super3.org
http://super3.org

**Comment by d5000** [comment]
German translation is ready, with the exception of Myth #2, which is still discussed at Peercointalk.. So when the CMS is installed, I can add it to the website.

**Comment by FuzzyBearBTC** [comment]
for reference the forum thread discussion on peercoin.net translations is here http://www.peercointalk.org/index.php?topic=1630.0
