### ISSUE TITLE
Rethink Bounty Process

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#133]
If we switch over to a CMS we need to rethink out current [tip4commit](http://tip4commit.com/projects) strategy. Some notes:
- Can request back our funds from [tip4commit](http://tip4commit.com/projects), and put them toward a manually paid bounty system?
- Can we perhaps keep the template files for Peercoin.net in the repository, and still use it for issue tracking, empty commits for auto-payment, and occasional design updates.

**Comment by Gnewt** [comment]
I would be happy to host a [BitHub](https://whispersystems.org/blog/bithub/) instance for Peercoin.net to give us finer grained control, if there is interest in that at all. I particularly like the ability to mark a certain commit as a FREEBIE which allows very small changes not to be counted in the auto-payout system.

I also think it's worth looking at other choices like [Jekyll](http://jekyllrb.com/) or another static site generator.. Static site generation from Jekyll allows a lot of the wonderful features of CMSes while still allowing the site to be generated from a GitHub repo. We could keep the templates and the content separately in the same repository. I still like the idea of the content itself being hosted in a GitHub repo.

**Comment by Gnewt** [comment]
For example, a pull request that just removes an arbitrary space can be marked with the message "//FREEBIE" to be exempt from the bounty system.

**Comment by super3** [comment]
I think that we be great. I'm totally OK with paying out, and I want to encourage small fixes, but of course they should get a relative amount like $1. Perhaps the payout should be be based on a ranking system from 1 to 5 based on the quality of the commit 

1 - Comma Fix
5 - Major Feature Addition

**Comment by super3** [comment]
As much as I like Github, I think this presents a barrier for other users who would like to contribute. They don't have the experience with Github and HTML, which is 75% of the work. What we need is more content and translations. 

This is why I went with Fork because I think it would allow us to do all those things with ease.

**Comment by Gnewt** [comment]
I've contacted tip4commit to ask about their policy for returning funds.

I've also played a bit with (BitHub)[https://github.com/WhisperSystems/BitHub] and I think it looks very promising. I could easily fork the repo and add varying levels. Right now it already gives us the ability to mark useful commits with "MONEYMONEY" and only pay out for those, but I like the idea of paying for every commit on a sliding scale of usefulness.

If we choose to use BitHub, a free Heroku instance will be more than sufficient and provides some nice isolation. I'm also happy to host it on my personal VPS but I think having it isolated from other software is good when it's handling Bitcoin.

**Comment by Gnewt** [comment]
tip4commit had this to say:

```
Thanks for contacting us.

There is no such feature as refund in Tip4commit, donations are considered anonymous and non-refundable. But we can probably create a fake tip to your address if you sign your refund request with your address 18NqGuyqo3d4vf2WRtHB2Ys1Gp1kw6FmaX.

The original idea of the service was not to facilitate outsourcing of the project development, but to support opensource projects by crowd funded tips.

But we are interested in development of the demanded features in tip4commit. Would you stay with us if we open the sources?

Thanks!
```

So first off, is that a Bitcoin address you own, @super3?
I would prefer hosting a BitHub instance where we can control the tip levels but that's just my own opinion.

**Comment by super3** [comment]
Yes, I believe so. I started the repo donation, and donated 1 BTC.

Honestly, I think we could totally stay with tip4commit if they open sourced the code. At this point we only need one feature, the ability to pay very small tips, for the super small fixes that people submit.

I'm pretty sure Peercoin.net has paid out more tips than the rest of the website combined.
