### ISSUE TITLE
Rewrite URLs (fancy, without .php)

### ISSUE THREAD

**Issue by jooize** [super3/peercoin_website_old#134]
Rewritten URLs look far better and make changing the engine providing pages simpler in the future.

I don't know how pages are managed right now, but I see Apache 2.2.22 is used.
https://httpd.apache.org/docs/2.2/rewrite/
### Effect

```
http://peercoin.net/minting.php
http://peercoin.net/downloads.php
http://peercoin.net/index.php
```

would become

```
http://peercoin.net/minting
http://peercoin.net/downloads
http://peercoin.net/
```

**Comment by Gnewt** [comment]
super3 is implementing a CMS soon, which should allow pretty URLs. I think this should wait until after the CMS is implemented.

**Comment by super3** [comment]
Yeah ideally we would be using mod_rewrite, but I'm just being lazy. The CMS might not get done till February, so might be worth doing a mod_rewrite. If someone can do this, provide me with an SSH key via my email, and I'll give you server access.

**Comment by danbartram** [comment]
I just sent in a pull request, with some mod_rewrite rules (Pull #215).

You just need to check the server has mod_rewrite and .htaccess files enabled and loaded otherwise you'll get some 500 server errors.
