### ISSUE TITLE
Myth #2 cointains errors

### ISSUE THREAD

**Issue by d5000** [super3/peercoin_website_old#135]
As we have seen in the reddit/Peercointalk discussion regarding checkpointing, Sunny King's cite in Myth #2 is reffering to Primecoin (XPM), not to Peercoin (PPC). So this must be changed, otherwise we are spreading misleading information.

My suggestion (please correct if there are grammatical/stylistic errors, as I am no english native speaker):

---

Checkpoints are an additional security measure and were introduced to protect the Peercoin network from attacks when it was in its infancy. Sunny King explains:

"The risk of 51% denial-of-service attack on block chain is real, especially to a smaller network. In fact I wouldn’t exclude such a possibility to even bitcoin. Of course such an attack on bitcoin would likely not come from an individual due to the resource required. But it’s irresponsible to say that’s not possible. Just imagine what would happen if bitcoin stops processing transactions for a few days."

As Peercoin's network has grown substantially in the past year, checkpoints will be phased out in one of the next versions, probably in PPC 0.5.

---

**Comment by Gnewt** [comment]
I almost included this in my last commit but left it alone because I figured we wanted the quote to stay native. If we do away with the quote (which I personally think is a good idea), something like this would be beneficial. I am not a fan of how the quote is written and I think it takes away from Peercoin's sense of legitimacy.

**Comment by super3** [comment]
Just come up with something better and we will replace it. I'm not tied to it, its just what we have.

**Comment by d5000** [comment]
Is my suggested text too bad English, or why is there a need for another text?

**Comment by super3** [comment]
I believe this was fixed with #138
