### ISSUE TITLE
bitaddress

### ISSUE THREAD

**Issue by pffff** [super3/peercoin_website_old#14]
link to bitaddress is missing 

https://web.archive.org/web/20131022083840/http://ppcoin.org/bitaddress

**Comment by super3** [comment]
Rather not rely on the archive.org copy. Do you think you could contact Sunny and ask for the original webpage?

**Comment by pffff** [comment]
I'll try to contact him and get the original webpage for it

**Comment by d5000** [comment]
Thanks for opening this. There are some web services which require such a tool, so it's important for Peercoin's success.

**Comment by super3** [comment]
Found it. https://github.com/ppcoin/bitaddress.ppc

**Comment by super3** [comment]
Hmmm. That doesn't look right. Closing until someone can find the original Peercoin BitAddress.

**Comment by pffff** [comment]
maybe just link to http://primecoin.org/bitaddress ?
