### ISSUE TITLE
Faucet

### ISSUE THREAD

**Issue by pffff** [super3/peercoin_website_old#15]
the faucet has been lost during the redesign, imo it should come back somewhere
http://ppcoin.org/faucet
https://bitcointalk.org/index.php?topic=149165.0

**Comment by super3** [comment]
I don't have core code to that faucet. I do have my own faucet software, but it would require excessive work and maintenance to get it working. Without implementing `sendtomany` the faucet balance would be killed quite quickly. If someone wants to put in 1000 PTS+ bounty I can hire someone to get this done, but at this point I am going go focus on static for now.
