### ISSUE TITLE
Ticker Looks Broken

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#154]
Returning 0 values:

```
{"price":0,"market_cap":0,"total_supply":0}
```

**Comment by Gnewt** [comment]
That's because CoinMarketCap is showing all "?" for Peercoin :/... what gives? I can contact them if you'd like.

**Comment by super3** [comment]
Our block explorer is down so they can't resolve our block count. Can you
please contact them with the new one

http://blockexplorer.peercointalk.org

**Comment by Gnewt** [comment]
I sent Gliss (the maintainer of CMC) a PM on BitcoinTalk with a link to the new block explorer. I'll update this issue when Gliss responds.

**Comment by Gnewt** [comment]
@super3, Gliss asked me: "hey, would you be able to enable the API so I can grab the total money supply?"
Are you in touch with the operator of the block explorer?

**Comment by super3** [comment]
I think it's Fuzzybear from the forum.

**Comment by Gnewt** [comment]
The ticker is working again (has been for a little bit). I let Gliss know to talk to Fuzzybear.

**Comment by super3** [comment]
Perhaps we need to upgrade tickerinfo.php. The current system works, but I think the way we implemented it doesn't seem scalelable.

**Comment by Gnewt** [comment]
Happy to change it up. Are your concerns on scalability based on the fact that it sources data from CoinMarketCap, or that the update mechanism is not separate from the mechanism that presents the data to the user? Currently the server won't make requests to CoinMarketCap any more frequently than 30 seconds apart.

**Comment by super3** [comment]
Well now that you say that we should have 2 sources to get this data from. And if they both fail then it should be automatically disappear from the front page instead of displaying errors on the front page.

Secondly we need to implement it 100% client side with javascript. The PHP tickerinfo.php will be an external API that we can all on a separate server.

**Comment by super3** [comment]
Both. It works fine I just want to address all the points of possible
failure.
