### ISSUE TITLE
Can you Replace the Wood Paneling with the new Dark Background

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#16]
Hey Super3, you asked in one of the threads for the new logo files. Me, MeBeingAwesome and a couple others were actually talking last night if it was possible to switch out the wood paneling at the top of the website for the dark background with the logo and text. If you haven't seen it yet, I included it below. Here are the files. All the new ones are in the folder called Peercoin Text Files...

http://www.peercointalk.org/index.php?topic=862.0

http://i2.photobucket.com/albums/y17/Sentinelrv/Other-Images/logotextdarkbg2.png~original

**Comment by Sentinelrv** [comment]
I need to know what dimenions the wood paneling is so I can make a banner. Also, it's important to know if you're going to want the logo and text in the same placement as it currently is, or if it can all be centered on the banner. It would be much easier to do this and I think a cleaner look if it was all centered like it is in the new images. I don't think I'd have to change anything either.

**Comment by super3** [comment]
@Sentinelrv Updated. Look good enough?
