### ISSUE TITLE
Add Physical Contact Info

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#166]
Needs to be added to [http://peercoin.net/downloads.php](http://peercoin.net/downloads.php)

**Comment by Gnewt** [comment]
What do you mean by Physical Contact Info?

**Comment by super3** [comment]
No idea. That is just what Google wanted.

**Comment by Gnewt** [comment]
For AdSense? Hmm... I found some documentation of that phrase [here](https://support.google.com/adwordspolicy/answer/2464998?hl=en), but it seems to be geared toward those providing a financial service. Peercoin.net just provides information.

**Comment by super3** [comment]
Agreed. Should we just not include anything there?

**Comment by Gnewt** [comment]
Sounds good.
