### ISSUE TITLE
Add Terms of Service

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#167]
Terms of Service (TOS) or End User License Agreement (EULA.) Ideally the EULA would be right next to every download button.

**Comment by Gnewt** [comment]
What type of TOS or EULA do you have in mind? Is there a specific license you'd like to use?

**Comment by super3** [comment]
No idea. Pick one that works best, and we can go from there.

On Wed, Feb 5, 2014 at 9:55 PM, Nick Mooney notifications@github.comwrote:

> What type of TOS or EULA do you have in mind? Is there a specific license
> you'd like to use?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/super3/peercoin.net/issues/167#issuecomment-34287504
> .

## 

Shawn Wilkinson
Bitcoin Developer/Entrepreneur/Enthusiast
(1P4QkLsujBPBZyUwDezikL4fUSs7JvFhPv)
me@super3.org
http://super3.org
