### ISSUE TITLE
Network statistics

### ISSUE THREAD

**Issue by czarly** [super3/peercoin_website_old#17]
I would like to have network statistics. Maybe to play around with as a fancy moving JavaScript. Information like number of nodes, location of nodes, transactions per second, approximately energy consumption in the last 24 hours etc.

**Comment by super3** [comment]
This should be the function of a blockchain.info like website, not the function of the informational website. I would like to see a live stat of approximately energy consumption saved in the last 24 hours etc as a selling point. Not currently a priority though.
