### ISSUE TITLE
Dummy Proof PoS Explanation 

### ISSUE THREAD

**Issue by czarly** [super3/peercoin_website_old#18]
Since this is the main issue when talking to people and preparing presentations, it is very needed to make a colorful info graphic about Bob and Alan earning money by coinstake (interest) and securing the network on the way. It has to be Sesame Street style and should include copy&paste material for talks on bitcoin conferences. They are searching for this kind of stuff endless and e best presenters are not usually the ones that are good at reading papers and source code.

**Comment by super3** [comment]
Agreed. Get someone to write this up, and I will include it.

**Comment by super3** [comment]
Partly done in #19 but I think we need a good PoS page.

**Comment by super3** [comment]
I think this is fixed as of e203c427e809c2f0e5c29865728917c929345c9d
