### ISSUE TITLE
Can we Fix the Slogan?

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#184]
From my understanding, the slogan used to say "The Sustainable & Secure Cryptocurrency." We then agreed on the forum to switch the words around so that it read "The Secure & Sustainable Cryptocurrency."

I asked Kappamale on the subreddit to fix the slogan to reflect this, but he notified me that even peercoin.net didn't say that. I checked and currently the slogan is shortened to just "Sustainable & Secure Cryptocoin" with the words in the wrong order.

I personally don't like the omission of "The." It sounds like an incomplete sentence the way it is right now. The words should also be switched back to "Secure & Sustainable." It sounds better.

The only thing I'm unsure of is the switch from cryptocurrency to cryptocoin. Certain people have argued in the past that we shouldn't call Peercoin a currency, because of its intended use as more of a long-term store of value. They've argued in favor of calling it a cryptocommodity. Rather than choosing one or the other, calling it a cryptocoin instead might be a nice middle ground. It's not as specific as calling it a currency or a commodity.

In the end it would be "The Secure & Sustainable Cryptocoin." What do you all think?

**Comment by super3** [comment]
I agree with you 100%

**Comment by super3** [comment]
Added to the Aesthetic and Brand Changes milestone.
