### ISSUE TITLE
redirect io to net?

### ISSUE THREAD

**Issue by rootsical** [super3/peercoin_website_old#186]
maybe there should be a discussion about this, but at the moment the peercoin.io address does not redirect to peercoin.net which could add to the confusion as to what the official website address is (i, however, prefer peercoin.io but i understand that now peercoin.net is pretty established). what you reckon? maybe not that important..

**Comment by super3** [comment]
Changed DNS settings for Primecoin.io, after they propagate I will forward the domain.

**Comment by rootsical** [comment]
i meant peercoin.io - you have it right?

**Comment by super3** [comment]
Redirects now.

**Comment by rootsical** [comment]
Nice!
