### ISSUE TITLE
Fix Price Ticker

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#187]
Under moderate load on a small server the website will fail, due to excessive requests from the ticker. I have remedied this by increasing the specs of the server, which allows the website to function properly. Even in this case the website will fail if we receive a large amount of traffic.

**Solutions**
- Modify the script to limit excessive requests. Most likely this is happening because we are using sqlite which was simply not build to handle this frequency. Perhaps storing the [db in memory](https://www.sqlite.org/inmemorydb.html) will be a quick fix for this?
- Make the script standalone and have http://peercoin.net call the external server for json data. This way the website will still load regardless of what happens with the ticker.

**Comment by Gnewt** [comment]
What does 'the website will fail' mean -- does the ticker fail to return data or does it have worse consequences on the rest of the site?

Either way, ideally, I would like to have the data updating as a daemon if we are going to serve it to clients (so clients only ever get cached data, that data is updated via cron or whatever). If we want to have the client always grab data from Vircurex for example, we'll have to update the cross domain policies so JavaScript can safely issue GETs to other domains.

In terms of SQLite, we can store the DB in memory if we can get a standalone service running. We could even simplify massively by sourcing data to the client from a flat file or something equally less complicated -- there's only three pieces of data that need to be served. A big issue right now is that the SQLite connection is re-initialized every time a request for the price is made.

**Comment by super3** [comment]
Server gets more requests than it likes and locks up. Can't even ssh or
anything.

Yeah I like the flat file idea. Let's do that?

**Comment by Gnewt** [comment]
Sure! Do you want to implement periodic updates via cron? That way client logic would just be reading from the file.

**Comment by Gnewt** [comment]
I could separate two files -- one to serve data to the client, one to update the data. The second one you could put in cron at whatever interval you'd like.

**Comment by super3** [comment]
Sure lets do that.

On Thu, Jan 30, 2014 at 2:33 PM, Nick Mooney notifications@github.comwrote:

> I could separate two files -- one to serve data to the client, one to
> update the data. The second one you could put in cron at whatever interval
> you'd like.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/super3/peercoin.net/issues/187#issuecomment-33724076
> .

## 

Shawn Wilkinson
Bitcoin Developer/Entrepreneur/Enthusiast
(1P4QkLsujBPBZyUwDezikL4fUSs7JvFhPv)
me@super3.org
http://super3.org

**Comment by super3** [comment]
My server bandwidth thanks you. 
![Imgur](http://i.imgur.com/0zfpwcL.png)

**Comment by super3** [comment]
Do you mind pushing this update to the primecoin.io site as well? Uses the same code.
https://github.com/super3/primecoin.io

**Comment by Gnewt** [comment]
Awesome, nice to see. I'm sending in a pull request to Primecoin's as soon as my git client stops acting funky.

**Comment by super3** [comment]
Github for windows?

**Comment by Gnewt** [comment]
Naw just CLI git, I think I was having network issues.

**Comment by super3** [comment]
Ah.
