### ISSUE TITLE
Can we Rearrange the Top of the Website Like this?

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#19]
Now that we have a text logo, the Peercoin text in the upper left corner of the website is redundant. I believe we should remove it to make room for more menu buttons. Once it's gone, we should move all the existing menu buttons over to the left. We'll then have more room on the right to include all our social media icons: Facebook, Twitter, Reddit, etc... Then if possible, I'd like to see the logo and Peercoin text on the right side made larger. Here is a concept image I made to show how things should be...

http://i2.photobucket.com/albums/y17/Sentinelrv/Other-Images/PeercoinnetConcept2.png~original

Is it possible to do these things? I think it would make it a lot better.

**Comment by super3** [comment]
ACK. Will get to work on this one.

**Comment by Sentinelrv** [comment]
Hey Super3, in case you haven't started to work on this yet, I thought of a way to improve it even further, at least in my opinion. I think we should remove "Decentralized Money" and replace it with the new Peercoin text logo, rather than having it under the coin logo. I think it's important to have a large "Peercoin" title on the left side where most people first look when they visit a page. And then on the right side you can just make the coin logo larger without the text underneath. There is a file in my download just for the Peercoin text logo, without the coin logo attached. You can use that. What do you think?

**Comment by Sentinelrv** [comment]
Here is an updated concept image...

http://i2.photobucket.com/albums/y17/Sentinelrv/Other-Images/PeercoinnetConcept3.png~original

**Comment by super3** [comment]
Even better. I think we should update the blurb. We assume that already know what Bitcoin is if they are visiting Peercoin. We should say something about energy efficiency, and interest via proof of stake.

**Comment by Sentinelrv** [comment]
That would be good too. Tomorrow if I get a chance I'll make a thread about it.

**Comment by Sentinelrv** [comment]
I think we've finally sorted out the short description to go up on the website...

"Peercoin offers technological advances over Bitcoin that allow its network to consume far less energy and achieve a higher degree of security and decentralization.  Not only is Peercoin's energy efficient design "greener" than the alternatives, it is set up to reward you just for owning the coins. In this way, even if you are not a "miner" your coin stash will be able to grow."

How is the change coming along anyway? I haven't heard anything about it since your last post on here. Do you have everything you need?

**Comment by super3** [comment]
Busy with coin and school work. You can use the Github editor to edit the text, and then just put in a pull request, and I will accept it.

**Comment by super3** [comment]
The description is a bit too long to go in the header. Do you think we can reduce that to about half that size?

**Comment by Sentinelrv** [comment]
Half the size? Is there anyway we can reduce the font size some to fit more in? That will cut out a lot of what we came up with. If not, I'll try to cut it down.

Also, sorry about not doing what you asked. I'm not completely familiar with how to use Github and haven't had the time yet to look up what you were asking me to do.

**Comment by Sentinelrv** [comment]
Ok, I made 3 different versions. 1 is the best, but longest description. 2 is ok. 3 is too short and not descriptive enough in my opinion. If possible to fit it in, go with 1.
1. Peercoin offers technological advances over Bitcoin that allow its network to consume far less energy and achieve a higher degree of security and decentralization. This is achieved through an innovative minting algorithm that places money production in the hands of currency holders.
2. Through use of an innovative minting algorithm, Peercoin offers technological advances over Bitcoin that allow its network to consume far less energy and achieve a higher degree of security and decentralization.
3. Peercoin offers technological advances over Bitcoin that allow its network to consume far less energy and achieve a higher degree of security and decentralization.

Also, I have all the logo files with updated shadows. I just have to upload them. I'm too tired tonight though to sort through them all, so I'll post the download link here tomorrow in case you need it.

**Comment by super3** [comment]
Social don't fit well at top, but they are in there. Open a new issue if I missed anything.
