### ISSUE TITLE
links to exchanges incomplete

### ISSUE THREAD

**Issue by Lamz0rNewb** [super3/peercoin_website_old#2]
the link list to exchanges is incomplete and might be restructured as in the last row are 2 exchanges which is quite confusing. suggestion:

Vircurex    https://vircurex.com/welcome/index?alt=ppc&base=btc&locale=en
BTC-E   https://btc-e.com/exchange/ppc_btc
MCX Now https://mcxnow.com/exchange/PPC
CoinMkt https://coinmkt.com/
Crypto-Trade    https://crypto-trade.com/trade/ppc_btc
BTER Exchange   http://bter.com/trade/ppc_btc
Cryptonit   http://cryptonit.net/exchange/btc/ppc
Cryptsy https://www.cryptsy.com/markets/view/28
Coins-e https://www.coins-e.com/exchange/PPC_BTC/

**Comment by super3** [comment]
Fixed in 8cce11c9bd9d600ab9840b092ccd8d9455a6858b
