### ISSUE TITLE
videos

### ISSUE THREAD

**Issue by rootsical** [super3/peercoin_website_old#20]
as requested on the peercointalk.org forum... nice one

**Comment by super3** [comment]
Can you link to the videos here as well?

**Comment by rootsical** [comment]
here you go.. 
http://www.youtube.com/playlist?list=PLBt4zAxcWonnA8-InWGUEw-UZofHdUIeT

**Comment by rootsical** [comment]
nice work.. just a little spelling error - it should be 'everything' in 'They cover everthing from setting up your first wallet'...
