### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by rootsical** [super3/peercoin_website_old#21]
how about a favicon with the new logo and transparency to look extra slick?

**Comment by super3** [comment]
I'll try to drop in a favicon after #19

**Comment by super3** [comment]
I need a copy of the logo in PNG with a transparent background.

**Comment by hireahenchman** [comment]
Hey I actually just finished fixing the logo up yesterday. Here’s both variations but with better letter spacing. Hope that helps :) 

Cheers

```
Chris Shelswell
```

Phone: (+64) 021 452255
Web: www.hireahenchman.co.nz

**Comment by super3** [comment]
Don't think Github will let you add attachments to a issue reply.

**Comment by hireahenchman** [comment]
Ah ok - You can download them from here then: http://www.hireahenchman.co.nz/downloads/peercoin_logos.zip

Cheers

```
Chris Shelswell
```

Phone: (+64) 021 452255
Web: www.hireahenchman.co.nz

**Comment by rootsical** [comment]
looking good..
