### ISSUE TITLE
"Everything" is Missing its "y"

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#23]
In the following paragraph, the word "everything" is missing it "y."

"We have developed a series of short video tutorials to help get you started. They cover everthing from setting up your first wallet, to trading and using Peercoin. Enjoy!"

**Comment by super3** [comment]
Don't trust me with writing after 12am. Fixed per d3291a962fb8ee2b5b1c84d60f12f385fbdff394
