### ISSUE TITLE
Here are Tiny Social Media Icons to Place in the Top Right (White Icons Look Best)

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#25]
I don't know if you got my PM, but I opened this anyway because I believe it's too important. We need those social media icons in a high traffic area and the top right portion of the website is all open space. There are plenty of tiny minimalist icons available in the link below to choose from. I think its best to choose white icons, which would go perfect with all the buttons you have up there now...

https://www.google.com/search?q=minimal+social+media+icons&rls=com.microsoft:en-US:IE-SearchBox&source=lnms&tbm=isch&sa=X&ei=FvKOUpjEEMqHkQedn4DoBw&ved=0CAkQ_AUoAQ&biw=1536&bih=718#imgdii

Also, I don't know if you want to replace the current logo with the one with the updated lighter shadows, but here are all the new files for it...

http://www.mediafire.com/download/9qf4iiqihla641r/Peercoin%20Logo%20Files.zip

**Comment by hireahenchman** [comment]
Hi - I don’t think i did get a PM. Was it via github? As I say i’m pretty useless at GitHub having never had to use it. I could certainly help fix up the social icons though you’ve kind of got me at a bad time. I’m away for the next week (leaving in about an hour) to go and get married. I think I’d get in a lot of trouble if I work too much. I may get an opportunity to photoshop up a mock design of what I think it could look like if that would help? I also agree nice flat social icons are a lot nicer.

Do you have a current photoshop mock I could work from? If not I can just put something together. 

Cheers
Chris

```
Chris Shelswell
```

Phone: (+64) 021 452255
Web: www.hireahenchman.co.nz

**Comment by Sentinelrv** [comment]
Oh, I didn't know Super3 had someone helping him now. The PM I mentioned was to him. I don't have anything to give you but what's in that link. I don't want to get you in trouble, but it's very important that we get those icons/links up for Facebook, Twitter and Reddit before Monday when the New York Times article will hit. These links will funnel traffic into our social media pages, which we can then use for future promotion.

**Comment by hireahenchman** [comment]
ah all good I think i’m just getting email but don’t really know who they’re for :) - as long as you’re all sorted that’s sweet.

Cheers

```
Chris Shelswell
```

Phone: (+64) 021 452255
Web: www.hireahenchman.co.nz

**Comment by iheartcryptocoin** [comment]
Noticed we're already using Font Awesome, can just use the font awesome icons instead of searching for sprites on google, will work on this

**Comment by iheartcryptocoin** [comment]
Bad News, Font awesome has discontinued the reddit icon.  Here are three alrenatives we can download and use.  For now I am linking directly 

https://www.iconfinder.com/icons/60825/blue_button_facebook_social_icon#size=128

https://www.iconfinder.com/icons/60844/button_reddit_social_icon#size=128
https://www.iconfinder.com/icons/60859/blue_button_round_social_twitter_icon#size=128

**Comment by Sentinelrv** [comment]
Ben from the forum said he owns a bunch of different icons like the white ones I posted in chat earlier, so he's going to try to figure something out tomorrow. I think what you have on there right now is fine until he can get the better looking versions up.

**Comment by iheartcryptocoin** [comment]
ae0d91001296fee1b1224a8db1109a61ed0cb7df
