### ISSUE TITLE
'Read More' JS Broken

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#27]
Does not show the full text when expanded: 
![Imgur](http://i.imgur.com/5xngbTM.png)

**Comment by iheartcryptocoin** [comment]
This readmore works across browsers and platforms including landscape on mobile.  

However it is broken in portrait on mobile because the 3 columns are reducing to two very narrow columns instead of 1 wider column through the responsive behavior.

**Comment by iheartcryptocoin** [comment]
439c6ba97e831ea8bfc4c7da99c9c4aad89790aa
