### ISSUE TITLE
Repository Bot

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#278]
It's poor form to push changes to the live site to see if they work. It would be nice if we have something like [BitcoinPullTester](https://github.com/bitcoin/bitcoin/pull/3846), which runs tests on Bitcoin for every pull request. 

Perhaps our bot could return screenshots of every page affected by the commit, or return a URL to a temporary hosted page with the code result.

**Comment by iheartcryptocoin** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

**Comment by super3** [comment]
Anyone want to set that up?
