### ISSUE TITLE
Clean up 'Use Peercoin' Page

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#279]
Want to funnel a bunch of the people from the website into this page. I feel like we are missing tons of resources, merchants, etc. that should be on this page. 

A) Clean up the design into a bunch of pretty tables, instead of bulleted lists
B) Start a bounty pool for users to actively maintain and add to the page

**Comment by iheartcryptocoin** [comment]
Agree.  Have an example of a site using the layout you are thinking about?

**Comment by super3** [comment]
No, but I wanted it to be filled like this page https://en.bitcoin.it/wiki/Trade, but actually look good.
