### ISSUE TITLE
Make W3C Compliant

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#29]
Some broken tags. See [W3C Validator](http://validator.w3.org/check?uri=http%3A%2F%2Fpeercoin.net%2F&charset=%28detect+automatically%29&doctype=Inline&group=0).

**Comment by iheartcryptocoin** [comment]
Looks mostly like social media image issues, I'll fix that first.  Then can strategize how to tackle previous message

Date: Sat, 23 Nov 2013 16:02:15 -0800

**Comment by super3** [comment]
Please include the commit where this issue is fixed.

**Comment by iheartcryptocoin** [comment]
ff5ca99053c41dcbe4e2807a44dd0428406a49a8

**Comment by super3** [comment]
Ok. You can also fix from then commit by saying "Fixes #29" in the commit message

**Comment by iheartcryptocoin** [comment]
I added a comment to the commit when closed this. How do you change the title itself?  It looks locked
