### ISSUE TITLE
Peercoin Listed Twice in Upper Left Corner?

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#296]
Is there a reason why it says Peercoin twice in the upper left corner of the page? First it shows it in logo form which I understand, but then it says it again right before the slogan. It's a little redundant and takes up unnecessary space in my opinion. Unless it's intended for search engines to capture it. If that's the case, nevermind.

While I'm making this post, is there any way we could make the text logo a tad larger? It's too small in my opinion. I can barely tell that there's a leaf on the i. It doesn't have to be huge, just a little larger than it currently is, so I can make out some more detail.

**Comment by super3** [comment]
Looks like someone snuck this change into the translation strings. I just need to be better at looking at the diffs. 

Open a separate issue for the logo.
