### ISSUE TITLE
links to ppc pools might be adjusted

### ISSUE THREAD

**Issue by Lamz0rNewb** [super3/peercoin_website_old#3]
the links to pools currently cointain only coinotron and d7's pool. fuzzy's pool and ppc.fixx.ru might be added:

FuzFuzzypool    http://fuzzypool.org/pool/
Fixx    http://ppc.fixx.ru/index

**Comment by super3** [comment]
Fixed in 8cce11c9bd9d600ab9840b092ccd8d9455a6858b
