### ISSUE TITLE
Need larger Coin logo for social media

### ISSUE THREAD

**Issue by iheartcryptocoin** [super3/peercoin_website_old#30]
https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fpeercoin.net

FB complaining

**Comment by Sentinelrv** [comment]
Do you need the link to our logo files? There are larger versions in there, as well as ones including the shadow under the coin. Here it is...

http://www.mediafire.com/download/9qf4iiqihla641r/Peercoin%20Logo%20Files.zip
