### ISSUE TITLE
Can we Make the Peercoin Text Logo a Little Larger?

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#302]
Is there any way we could make the text logo in the upper left corner a tad larger? It's too small in my opinion. I can barely tell that there's a leaf on the i. It's also so small that it has jagged edges, rather than smooth ones. Here is what I currently see...

http://i2.photobucket.com/albums/y17/Sentinelrv/Other-Images/PPCLogoTooSmall.png~original

It doesn't have to be huge, just a little larger than it currently is, so I can make out some more detail and the jagged edges are gone.

**Comment by iheartcryptocoin** [comment]
will be done - see my comment at #295
