### ISSUE TITLE
Major bug with the latest commits.

### ISSUE THREAD

**Issue by bardiharborow** [super3/peercoin_website_old#304]
Screenshot: http://gyazo.com/d72f0841afd5cabee5165e65d7530beb
Last good commit: 87f92d3e32f474404d76f7fbdfb230a39985aa84

**Comment by iheartcryptocoin** [comment]
commit was taking longer than typical to show live so was testing server responsiveness - all works

**Comment by super3** [comment]
Yeah, we really need to have a development branch. I'll try to get around to is this weekend.
