### ISSUE TITLE
Long term content management

### ISSUE THREAD

**Issue by iheartcryptocoin** [super3/peercoin_website_old#31]
What can we do about a long term CMS?  Amongst other things, we'll need an area for all of the different news coverage,  a space for update videos, potentially a more organized archive of the weekly newsletters, lists/reviews of exchanges (and payment) processors as they come online etc etc.  

What're we thinking for organizing this?

**Comment by iheartcryptocoin** [comment]
Shawn,

@Sent and I made a few final tweaks (two spelling errors and moved social icons).  Can you take a look and update live site at your convenience?  

If there is a way to update live site from GH directly let me know and I'll save you the time

**Comment by super3** [comment]
We will need to talk about commit and release strategy before I enable automatic updates.

**Comment by super3** [comment]
These seem like some good solutions:
- [Pico](http://pico.dev7studios.com/)
- [Fork-CMS](http://www.fork-cms.com/)
- [Anchor CMS](http://anchorcms.com/)
