### ISSUE TITLE
Tip4commit and Peer4commit

### ISSUE THREAD

**Issue by bardiharborow** [super3/peercoin_website_old#319]
This repo has 2.49488921Ƀ waiting for it on tip4commit and 2432.07756800 PPC  waiting for it on peer4commit.  Seeing as it is deprecated, should we contact tip4commit and peer4commit and have the balances transferred to the new repo?

http://tip4commit.com/projects/222

**Comment by sashazykov** [comment]
I would like to transfer it, since I don't want to store this money. Where is the new repo? Could repo owner agree on transfer of funds?

**Comment by sashazykov** [comment]
@super3 ?

**Comment by super3** [comment]
Does it have to be transferred to a new repo or can I transfer it to a development fund address?

**Comment by sashazykov** [comment]
@super3 I would prefer to transfer it to another project. Sponsors apparently wanted to use tip4commit.

**Comment by super3** [comment]
My main concern is that that peer4commit only pays out per commit. Someone might write a huge feature or someone might fix a missing period, and they are valued the same. Yes, owners can decided tip amounts, but still it doesn't convey that to the people actually committing. 

What I think peer4commit needs as a feature is the ability for repo owners to assign a bounty to a particular issue. That way the project can move forward with funding. A single commit is not a good metric for worth.

**Comment by sashazykov** [comment]
Unfortunately, we don't have a mechanism of refunding deposits now. I've changed gihub_id of the project and put tips on hold, so you can log in, add policy and decide tip amounts for all existing commits. Project url is the same http://tip4commit.com/projects/222

**Comment by super3** [comment]
Ok, I will figure out a solution for this in the next couple of days.

**Comment by super3** [comment]
I've moved most of the funds to the website funds, and the other Peercoin.net repo. Should be solved.
