### ISSUE TITLE
Please Add Logo with Shadow Underneath (Concept Image Inside)

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#34]
I made up a concept image of the logo with the shadow under it on the website and I think it looks a hundred times better. It really makes it pop out at you. Here it is...

http://i2.photobucket.com/albums/y17/Sentinelrv/Other-Images/PPCWebsiteLogoShadow.png~original

Here are all the logo files in case you need them. Go to this path to find the right image:

Path: Peercoin Logo Files\Icon Only\With Shadow

All Logo Files:
http://www.mediafire.com/download/9qf4iiqihla641r/Peercoin%20Logo%20Files.zip

**Comment by iheartcryptocoin** [comment]
Would if I could, but  still cannot upload image files to the repo.  #30 is directly related to this as well - we need to host a slightly larger logo for social media outfits to pull when link gets posted/ also look good on retia displays.  This is all low priority but if the images are being uploaded please make sure to copy a high res version directly into our images folder so it can be linked as well

**Comment by Sentinelrv** [comment]
The voting is over and people want to see this happen.

**Comment by super3** [comment]
Having trouble sizing it correctly. The shadow logo is in the /img directory if @iheartcryptocoin want to take a swing.

**Comment by Sentinelrv** [comment]
Are you guys still having trouble with this?

**Comment by super3** [comment]
New website, new design. If this is still relevant after the new design, let me know and I will reopen.
