### ISSUE TITLE
Recuit for team roles

### ISSUE THREAD

**Issue by iheartcryptocoin** [super3/peercoin_website_old#36]
1-2 SCRUM/otherwise AGILE familiar folks
1-2 UX experts
2 additional HTML/CSS/JS experts
2 additional committed content editors
4-5 Text\Article Writers 
2-3 Graphics experts
2-3 Video experts for improved youtube tutorials

**Comment by super3** [comment]
Agreed. I think the Text/Article writers are the top priority though.

**Comment by iheartcryptocoin** [comment]
Let's loop John in on this and see who he has on the volunpeer list

**Comment by super3** [comment]
Don't think any more progress can be made on this issue on Github. I think this is more a recruiting task. Closing for now.
