### ISSUE TITLE
horizontal scroll bar

### ISSUE THREAD

**Issue by rootsical** [super3/peercoin_website_old#38]
![website_h_scroll_bar](https://f.cloud.github.com/assets/1428831/1609456/b72e09d8-5544-11e3-8624-f4d92ed0a723.png)

horizontal scoll bar should not show i guess?

**Comment by super3** [comment]
Meh. That shouldn't happen. Some more details so we can figure out how to fix it?

**Comment by iheartcryptocoin** [comment]
Can you check to make sure your browser zoom isn't on some weird level?

What bowser/OS are you using?

**Comment by super3** [comment]
Closing until @rootsical can provide us more details so that we can fix this issue.

**Comment by rootsical** [comment]
sorry, i should have said, it's been fine for a while..

**Comment by super3** [comment]
Cool. Thanks for the heads up.
