### ISSUE TITLE
Peercoin.net Forwarding

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#4]
Please make it so that all who click on ppcoin.org or ppcoin.com get FORWARDED to peercoin.net and that peercoin.net shows up on the browser address bar. It's confusing otherwise.

People still searching for ppcoin.org don't know the address has been changed to peercoin.net. Fixing this will let them see that the address has been changed. It will also help speed up the name transition from ppcoin to Peercoin.

**Comment by super3** [comment]
I have no control over the ppcoin.org domain. That is Sunny King right? He or whoever controls it needs to setup a 301 redirect instead of just a forward.

**Comment by Sentinelrv** [comment]
Ok, I'll let Sunny know then.

**Comment by super3** [comment]
As this is not in my hands, will close for now.
