### ISSUE TITLE
mining links

### ISSUE THREAD

**Issue by pffff** [super3/peercoin_website_old#49]
replace  http://fuzzypool.org/pool/  with http://theseven.bounceme.net/~theseven/pool/

Right now it links to fuzzypool, where nobody is mining, and it doesn't even seem to work. TheSevens pool is working, and people are mining there actively

**Comment by super3** [comment]
Create a Fork of the repo. Go to the index.html page, and click the edit button. Commit it, then submit a pull request here.

**Comment by super3** [comment]
Fixed in b8238119a87edee52afc9aacd8ed80a5f9ab1e3d
