### ISSUE TITLE
video doesn't fit in responsive mobile website

### ISSUE THREAD

**Issue by iheartcryptocoin** [super3/peercoin_website_old#52]

**Comment by iheartcryptocoin** [comment]
7c1db57a05

**Comment by iheartcryptocoin** [comment]
Shawn - already fixed - assigned to you to keep in loop

**Comment by super3** [comment]
Cool. That is better.

**Comment by iheartcryptocoin** [comment]
initially tested the bootstrap column css to try to force a resize.  Didn't work at all as you saw.  

We have to go with the hardcoding for now, in lieu of a finding framework that can make video containers responsive
