### ISSUE TITLE
Install CMS System

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#54]
Per #31. These seem like some good solutions:
- ~~[Pico](http://pico.dev7studios.com/)~~
- [Fork-CMS](http://www.fork-cms.com/)
- ~~[Anchor CMS](http://anchorcms.com/)~~

**Comment by iheartcryptocoin** [comment]
good research, will take a look at these this evening

**Comment by super3** [comment]
Ideally most of the website will remain static HTML. Might add some PHP just to make templating easier. 
We will add one of those 3 CMS systems for managing our Docs/Help sections.

**Comment by super3** [comment]
Looks like I will be using Fork CMS for this as it supports multiple languages.

**Comment by iheartcryptocoin** [comment]
What about Pico?  Flat file CMS could be a solid solution since only devs update the site

http://pico.dev7studios.com/docs.html#blogging
