### ISSUE TITLE
Increase Pagecount

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#55]
Template is currently on the 'index.html' page. 
- [x] Split into a header, page body, and footer.
- [x] Use SSS(perhaps PHP), to join fragments

Bounce rate is too high. Need to add additional content pages:
- [x] Mining Info
- [x] Exchange Info

Furthermore: 
- [ ] Download Page
- [ ] Video Tutorial Page(s)
- [ ] What is Proof of Stake?

**Comment by iheartcryptocoin** [comment]
- [ ] Written tutorials  (install wallet, mod for PoS, etc)
- [ ] FAQ 
- [ ] Glossary of Common Terms

**Comment by super3** [comment]
See issues #100, #99, #97
