### ISSUE TITLE
Template Change?

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#56]
Original:
- [Fasi - Responsive Mobile App Theme](https://wrapbootstrap.com/theme/fasi-responsive-mobile-app-theme-WB061D706)

Perhaps something better?
- [GOOD - Flat Corporate Theme](https://wrapbootstrap.com/theme/good-flat-corporate-theme-WB0708887)

**Comment by Sentinelrv** [comment]
I don't know about that. I really love what you have up there now. The design was even complemented on by a recent news article as a reason people might want to invest their money in us.

**Comment by super3** [comment]
With a little work I think we can out do it by several times.

**Comment by super3** [comment]
Addressed in [Good](https://github.com/super3/Peercoin.net/tree/good) branch.
