### ISSUE TITLE
Request to Add Press Tab

### ISSUE THREAD

**Issue by JohnManglaviti** [super3/peercoin_website_old#58]
Request to add a press tab (next to volunteers) that has a dropdown:

Press
- Articles and Interviews

Link to here: http://www.peercointalk.org/index.php?topic=1603.0
- Press Kit

Link to here: http://www.peercointalk.org/index.php?topic=1616.0
- Request an Interview  

Maybe a form that emails the following addresses:

john.manglaviti@gmail.com
sunnyking9999@gmail.com

**Comment by super3** [comment]
Way to crowded in the the top bar. Will need to figure out a better way to do this.

**Comment by super3** [comment]
Those need to be something other than empty to add them to the website.
