### ISSUE TITLE
Font and backdrop image. 

### ISSUE THREAD

**Issue by hammyburger** [super3/peercoin_website_old#6]
Ideas:

How about flipping out the fonts for something more serious. I suggested "Impact" for headings and "Times New Roman" for body in one forum thread. That said I'm not married to anything and I can't say there is consensus. Other ideas? The font now is rough.

And what do you think about flipping out the wood paneling for something else? The wood paneling gives the site the vibe that it is just a template we plugged some info into. Any ideas what we can do there?

**Comment by Sentinelrv** [comment]
The mobile site also has cursive font. I think that needs to be changed too.

**Comment by super3** [comment]
Can you guys post full screenshots of the website from your browser?

**Comment by Sentinelrv** [comment]
Here it is in Internet Explorer...

http://i2.photobucket.com/albums/y17/Sentinelrv/Other-Images/iepeercoinnet.png~original

Here it is in FireFox. Notice that in FireFox, "Peercoin" and "Features" are in Comic Sans, while in IE it's not...

http://i2.photobucket.com/albums/y17/Sentinelrv/Other-Images/ffpeercoinnet.png~original

And here are "Peercoin" and "Features" in cursive. The right side of the screen also seems to be cut off...

http://i2.photobucket.com/albums/y17/Sentinelrv/ip1peercoinnet.png~original

http://i2.photobucket.com/albums/y17/Sentinelrv/ip2peercoinnet.png~original

I think it looks best in IE right now.

**Comment by super3** [comment]
I made updates to the fonts across the board. Most of the fonts were not hosted on the website I fell back to things like Comic Sans. That should be gone now. Give me some feedback on the new fonts. 

Please split off the background image to another issue.

**Comment by Sentinelrv** [comment]
I like these fonts a lot better and they seem to be the same on all the browsers I'm using. The only problem I see that still remains is the right side of the mobile screen being cut off. Check the two photos I linked above.

**Comment by super3** [comment]
Ok we fixed the font, and the wallpaper will have to be a separate issue. Looks like that is a rendering bug with iPhone. Repost another issue with those screens. I'm probably going to have to get my hands on an iPhone and see whats wrong with the template.
