### ISSUE TITLE
Can you Replace the Peercoin Text in the Top Left with our Text Logo?

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#66]
We have two logos, the coin logo and the text logo with the leaf in it. I believe you should replace the generic Peercoin text in the top left with our text logo. It's the perfect place to put it. There are light and dark versions of the text logo. It might be best to use the dark version since it's on a white background.

**Comment by ghost** [comment]
+1, the logo would definitely look very nice. There's the text only ones (and others) here : http://sourceforge.net/projects/ppcoin/?source=dlp
