### ISSUE TITLE
Consolidating websites.

### ISSUE THREAD

**Issue by hammyburger** [super3/peercoin_website_old#7]
Do you need any assistance on moving peercointalk under "peercoin.net/forum" and wiki under "peercoin.net/wiki"?

**Comment by super3** [comment]
Last time I looked at that topic there was no general consensus on moving the forum. Lets take care of #7 then try to work on getting the wiki then the forum rolled in.

**Comment by super3** [comment]
Ok can someone contact the wiki admin, and get those files to be so I can host it on the server?

**Comment by Sentinelrv** [comment]
I messaged Nox to get in touch with you about it. He's the one who created the wiki that was on peercoin.net.

**Comment by super3** [comment]
It seems like we are going to create one from scratch. Probably have to wait a little bit till I launch an independent server just for Peercoin.
