### ISSUE TITLE
Adding a link from the main site to Peercoinmyths.com

### ISSUE THREAD

**Issue by JohnManglaviti** [super3/peercoin_website_old#8]
Request: Create a link to the Peercoinmyths.com site.

**Comment by Sentinelrv** [comment]
Probably stating the obvious here, but I would just call it Myths.

**Comment by super3** [comment]
No idea where that link should go. Needs to be discussed further.

**Comment by Sentinelrv** [comment]
Why not just add a "Myths" link at the top where the other main buttons are? It was my understanding that JustaBitofTime was working on the Myths section off-site and that once the text is finalized and ready to go, it will all be added to a separate page on main website at peercoin.net/myths. PeercoinMyths.com would then forward to that link. We would then do the same thing when we make the FAQ section.

**Comment by super3** [comment]
NAK, that top is getting cluttered. I think it will fit well under info.

**Comment by super3** [comment]
Added as of 0506e0ca604c9e3896641139f69c39501226ff13
