### ISSUE TITLE
Desktop Site Link

### ISSUE THREAD

**Issue by Sentinelrv** [super3/peercoin_website_old#9]
Can we please have a "Desktop Site" link at the bottom of the mobile version? A lot of people like me hate mobile sites and want to have the choice of viewing it how it was meant to be seen. I think this is low priority, so it can probably wait until later.

**Comment by super3** [comment]
Fair issue, but this would take some time and code to implement, and I would have to maintain both a static and desktop link vs just the static for now. Some of that time is probably better spent adding pages and content. 

Bootstrap offers some guidance on how to get this done though:
http://getbootstrap.com/getting-started/#disable-responsive

Once we have some more stuff on there then we can consider it. Some mobile browsers will allow you to disable mobile sites in the settings.
