### ISSUE TITLE
Create 'What is Proof-of-Stake' Basic Page

### ISSUE THREAD

**Issue by super3** [super3/peercoin_website_old#99]
This page should include very general introduction that the average Joe crypto can understand. Should probably contrast "Mining and Minting".

**Comment by Gnewt** [comment]
I'd be happy to write this up -- do you still want to do it, @Kerberus35?

**Comment by super3** [comment]
Go for it @Gnewt

**Comment by super3** [comment]
Fixed 77b7f67cbc13c19134fcf671c56d3a8f70c2eef5
